border:
  overworld: 1000

language: eng

death:
  lightning: true
  signs: true

map-number: 1
kit-map: false
# You can find your time zone here https://www.php.net/manual/en/timezones.php
time-zone: "America/Chicago"

end:
  enabled: true
  border: 400
  exit-location: "world,0.5,75,0.5,0,0"

nether:
  enabled: true
  border: 1000
  exit-location: "world,0.5,75,0.5,0,0"

# support BedrockEconomy, EconomyAPI, Capital
economy-provider: "BedrockEconomy"
capital-selector: